PT1_group = ['ROSN','MAGN','ALRS']
PT2ov_group = ['CHMF','GMKN','MOEX','SELG']
PST1_group = ['RUAL','HYDR']
PTA_R_group = ['MXI']
PTA_R5_group = ['TATN','CNY','FEES','ABIO']
PTA_R6_group = ['LKOH','NVTK','APTK','MTLR','VTBR','PIKK','GAZP','AFKS','SOFL','MRKP']
sleep_group = ['BSPB','SBER','SBERP']